[package]
name = "ldn"
version = "0.1.0"
edition = "2024"

[lib]

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
	"Win32_Devices_Usb",
	"Win32_Devices_DeviceAndDriverInstallation",
	"Win32_System_Registry",
	"Win32_Devices_Properties",
	"Win32_System_Console",
	"Win32_Storage_FileSystem",
	"Win32_Security",
	"Win32_System_IO",
	"Win32_System_WindowsProgramming",
] }

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
wrest = { workspace = true }

[build-dependencies]
bindgen = { version = "0.72.1" }

[target.'cfg(windows)'.build-dependencies]
# windows sucks https://learn.microsoft.com/en-gb/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN
dunce = { version = "1.0.5" }

[lints]
workspace = true